-- 0008_posts: blog / articles for SEO content marketing
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null default '',
  cover_image_url text,
  author text not null default 'نیلا گل',
  tags text[] not null default '{}',
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists posts_published_idx
  on public.posts (is_published, published_at desc);

-- keep updated_at fresh on every update
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.set_updated_at();

alter table public.posts enable row level security;

-- public (anon + authenticated) can read only published posts
drop policy if exists "posts public read published" on public.posts;
create policy "posts public read published"
  on public.posts for select
  to anon, authenticated
  using (is_published = true);

-- admins get full CRUD (combined with the public policy via OR, admins also read drafts)
drop policy if exists "posts admin all" on public.posts;
create policy "posts admin all"
  on public.posts for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());
