-- 0009_orders: base customer orders table; online payment fields are added in 0011_payments.
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  customer_name text not null,
  phone text not null,
  city text,
  address text,
  note text,
  items jsonb not null default '[]'::jsonb,
  subtotal bigint not null default 0,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_check check (status in ('pending','confirmed','shipped','delivered','canceled'))
);

create index if not exists orders_user_idx on public.orders (user_id, created_at desc);
create index if not exists orders_status_idx on public.orders (status, created_at desc);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

alter table public.orders enable row level security;

-- anyone (guest or logged-in) may place an order; length-guarded; a logged-in
-- user can only attach their own id (or leave it null as a guest)
drop policy if exists "orders insert" on public.orders;
create policy "orders insert" on public.orders for insert to anon, authenticated
  with check (
    (user_id is null or user_id = auth.uid())
    and char_length(customer_name) between 1 and 120
    and char_length(phone) between 4 and 30
    and char_length(coalesce(note, '')) <= 1000
    and jsonb_typeof(items) = 'array'
  );

-- a logged-in user reads their own orders; admins read all
drop policy if exists "orders select own or admin" on public.orders;
create policy "orders select own or admin" on public.orders for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- admins manage (update status / delete)
drop policy if exists "orders admin manage" on public.orders;
create policy "orders admin manage" on public.orders for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
