-- 0010_chat_messages: in-site live chat (logged-in customer <-> admin), realtime
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade, -- the customer thread owner
  customer_email text,                                                -- denormalized for admin display
  sender text not null check (sender in ('customer','admin')),
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists chat_user_idx on public.chat_messages (user_id, created_at);

alter table public.chat_messages enable row level security;

drop policy if exists "chat select own or admin" on public.chat_messages;
create policy "chat select own or admin" on public.chat_messages for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists "chat customer insert" on public.chat_messages;
create policy "chat customer insert" on public.chat_messages for insert to authenticated
  with check (user_id = auth.uid() and sender = 'customer' and char_length(body) between 1 and 2000);

drop policy if exists "chat admin all" on public.chat_messages;
create policy "chat admin all" on public.chat_messages for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- enable realtime (idempotent)
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end $$;
